# Bag-of-Words

[CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)

In [116]:
corpus = [
    'Natural Language Processing for Classification of Acute, Communicable Findings on Unstructured Head CT Reports: Comparison of Neural Network and Non-Neural Machine Learning Techniques', 
    'Lexicon Integrated CNN Models with Attention for Sentiment Analysis', 
    'Cross-domain Document Retrieval: Matching between Conversational and Formal Writings', 
    'Event Analysis on the 2016 U.S. Presidential Election Using Social Media',
    'Improving Document Clustering by Eliminating Unnatural Language',
    'Robust Coreference Resolution and Entity Linking on Dialogues: Character Identification on TV Show Transcripts',
    'Text-based Speaker Identification on Multiparty Dialogues Using Multi-document Convolutional Neural Networks',
    'Classification of Radiology Reports Using Neural Attention Models',
    'Deep Dependency Graph Conversion in English']

In [117]:
from sklearn.feature_extraction.text import CountVectorizer

vsm_1gram = CountVectorizer()
X1 = vsm_1gram.fit_transform(corpus)

In [118]:
for i, title in enumerate(vsm_1gram.get_feature_names()):
    print('%2d: %s' % (i, title))

 0: 2016
 1: acute
 2: analysis
 3: and
 4: attention
 5: based
 6: between
 7: by
 8: character
 9: classification
10: clustering
11: cnn
12: communicable
13: comparison
14: conversational
15: conversion
16: convolutional
17: coreference
18: cross
19: ct
20: deep
21: dependency
22: dialogues
23: document
24: domain
25: election
26: eliminating
27: english
28: entity
29: event
30: findings
31: for
32: formal
33: graph
34: head
35: identification
36: improving
37: in
38: integrated
39: language
40: learning
41: lexicon
42: linking
43: machine
44: matching
45: media
46: models
47: multi
48: multiparty
49: natural
50: network
51: networks
52: neural
53: non
54: of
55: on
56: presidential
57: processing
58: radiology
59: reports
60: resolution
61: retrieval
62: robust
63: sentiment
64: show
65: social
66: speaker
67: techniques
68: text
69: the
70: transcripts
71: tv
72: unnatural
73: unstructured
74: using
75: with
76: writings


In [119]:
print(X1)

  (0, 67)	1
  (0, 40)	1
  (0, 43)	1
  (0, 53)	1
  (0, 3)	1
  (0, 50)	1
  (0, 52)	2
  (0, 13)	1
  (0, 59)	1
  (0, 19)	1
  (0, 34)	1
  (0, 73)	1
  (0, 55)	1
  (0, 30)	1
  (0, 12)	1
  (0, 1)	1
  (0, 54)	2
  (0, 9)	1
  (0, 31)	1
  (0, 57)	1
  (0, 39)	1
  (0, 49)	1
  (1, 2)	1
  (1, 63)	1
  (1, 4)	1
  :	:
  (6, 47)	1
  (6, 48)	1
  (6, 66)	1
  (6, 5)	1
  (6, 68)	1
  (6, 35)	1
  (6, 22)	1
  (6, 74)	1
  (6, 23)	1
  (6, 52)	1
  (6, 55)	1
  (7, 58)	1
  (7, 74)	1
  (7, 4)	1
  (7, 46)	1
  (7, 52)	1
  (7, 59)	1
  (7, 54)	1
  (7, 9)	1
  (8, 27)	1
  (8, 37)	1
  (8, 15)	1
  (8, 33)	1
  (8, 21)	1
  (8, 20)	1


In [120]:
vsm_2gram = CountVectorizer(ngram_range=(1, 2))
X = vsm_2gram.fit_transform(corpus)

In [121]:
for i, title in enumerate(vsm_2gram.get_feature_names()):
    print('%2d: %s' % (i, title))

 0: 2016
 1: 2016 presidential
 2: acute
 3: acute communicable
 4: analysis
 5: analysis on
 6: and
 7: and entity
 8: and formal
 9: and non
10: attention
11: attention for
12: attention models
13: based
14: based speaker
15: between
16: between conversational
17: by
18: by eliminating
19: character
20: character identification
21: classification
22: classification of
23: clustering
24: clustering by
25: cnn
26: cnn models
27: communicable
28: communicable findings
29: comparison
30: comparison of
31: conversational
32: conversational and
33: conversion
34: conversion in
35: convolutional
36: convolutional neural
37: coreference
38: coreference resolution
39: cross
40: cross domain
41: ct
42: ct reports
43: deep
44: deep dependency
45: dependency
46: dependency graph
47: dialogues
48: dialogues character
49: dialogues using
50: document
51: document clustering
52: document convolutional
53: document retrieval
54: domain
55: domain document
56: election
57: election using
58: eliminat

In [122]:
X2 = vsm_2gram.fit_transform(corpus)
print(X2)

  (0, 87)	1
  (0, 93)	1
  (0, 110)	1
  (0, 114)	1
  (0, 9)	1
  (0, 106)	1
  (0, 111)	1
  (0, 117)	1
  (0, 30)	1
  (0, 132)	1
  (0, 42)	1
  (0, 75)	1
  (0, 159)	1
  (0, 124)	1
  (0, 66)	1
  (0, 28)	1
  (0, 3)	1
  (0, 116)	1
  (0, 22)	1
  (0, 68)	1
  (0, 128)	1
  (0, 85)	1
  (0, 104)	1
  (0, 148)	1
  (0, 86)	1
  :	:
  (7, 109)	1
  (7, 162)	1
  (7, 133)	1
  (7, 130)	1
  (7, 118)	1
  (7, 129)	1
  (7, 160)	1
  (7, 10)	1
  (7, 97)	1
  (7, 22)	1
  (7, 108)	1
  (7, 131)	1
  (7, 115)	1
  (7, 21)	1
  (8, 81)	1
  (8, 34)	1
  (8, 73)	1
  (8, 46)	1
  (8, 44)	1
  (8, 60)	1
  (8, 80)	1
  (8, 33)	1
  (8, 72)	1
  (8, 45)	1
  (8, 43)	1


# TF-IDF

[TfidfVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)

In [126]:
from sklearn.feature_extraction.text import TfidfVectorizer

vsm_tfidf = TfidfVectorizer()
X3 = vsm_tfidf.fit_transform(corpus)

In [127]:
print(X3)

  (0, 49)	0.209314469882
  (0, 39)	0.176790333648
  (0, 57)	0.209314469882
  (0, 31)	0.176790333648
  (0, 9)	0.176790333648
  (0, 54)	0.353580667296
  (0, 1)	0.209314469882
  (0, 12)	0.209314469882
  (0, 30)	0.209314469882
  (0, 55)	0.13581476794
  (0, 73)	0.209314469882
  (0, 34)	0.209314469882
  (0, 19)	0.209314469882
  (0, 59)	0.176790333648
  (0, 13)	0.209314469882
  (0, 52)	0.307428183496
  (0, 50)	0.209314469882
  (0, 3)	0.153714091748
  (0, 53)	0.209314469882
  (0, 43)	0.209314469882
  (0, 40)	0.209314469882
  (0, 67)	0.209314469882
  (1, 31)	0.301389086958
  (1, 41)	0.356835668915
  (1, 38)	0.356835668915
  :	:
  (6, 23)	0.227002758778
  (6, 74)	0.227002758778
  (6, 22)	0.261081420753
  (6, 35)	0.261081420753
  (6, 68)	0.309112597128
  (6, 5)	0.309112597128
  (6, 66)	0.309112597128
  (6, 48)	0.309112597128
  (6, 47)	0.309112597128
  (6, 16)	0.309112597128
  (6, 51)	0.309112597128
  (7, 9)	0.355474920167
  (7, 54)	0.355474920167
  (7, 59)	0.355474920167
  (7, 52)	0.309075181687


# Clustering

[Clustering Algorithms](http://scikit-learn.org/stable/modules/clustering.html)

In [133]:
from sklearn.cluster import KMeans
import numpy as np

Y1_kmeans = KMeans(n_clusters=2, random_state=0).fit_predict(X1)
Y2_kmeans = KMeans(n_clusters=2, random_state=0).fit_predict(X2)
Y3_kmeans = KMeans(n_clusters=2, random_state=0).fit_predict(X3)

In [134]:
print(Y1_kmeans)
print(Y2_kmeans)
print(Y3_kmeans)

[1 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 1 0]


In [135]:
from sklearn.cluster import SpectralClustering

Y1_spectral = SpectralClustering(n_clusters=2, random_state=0).fit_predict(X1)
Y2_spectral = SpectralClustering(n_clusters=2, random_state=0).fit_predict(X2)
Y3_spectral = SpectralClustering(n_clusters=2, random_state=0).fit_predict(X3)

In [136]:
print(Y1_spectral)
print(Y2_spectral)
print(Y3_spectral)

[0 1 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 1]
[0 0 1 1 1 1 1 0 1]
